name: PHP Tests

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:
  unit-tests:

    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        php: [ 7.4, 7.3, 7.2 ]
        os: [ubuntu-latest]

    steps:

      - name: set_matrix_data
        id: set_matrix_data
        uses: noobly314/share-data@v1
        with:
          share-id: matrix
          mode: set
          key: matrix
          value: ${{ matrix }}

      - uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: opcache, gd
          coverage: none

      - name: Validate composer.json and composer.lock
        run: composer validate

      - name: Get composer cache directory
        id: composer-cache
        run: echo "::set-output name=dir::$(composer config cache-files-dir)"

      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: ${{ runner.os }}-composer-

      - name: Install dependencies
        run: composer install --prefer-dist --no-progress

      - name: Run test suite
        run: vendor/bin/codecept run

  slack:
      name: Slack
      needs: unit-tests
      runs-on: ubuntu-latest
      if: always() 
      steps:
        - name: get_matrix_data
          id: get_matrix_data
          uses: noobly314/share-data@v1
          with:
            share-id: matrix
            mode: get
            key: matrix
        - uses: technote-space/workflow-conclusion-action@v2
        - uses: 8398a7/action-slack@v3
          with:
             status: failure
             fields: repo,message,commit,author,action,job,took
             icon_emoji: ':octocat:'
          env:
            SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
            MATRIX_CONTEXT: ${{ toJson(steps.get_matraix_data) }}
          if: env.WORKFLOW_CONCLUSION == 'success'
